version: 1
description: DeepSeek-V2-Lite MoE on 1 GPU
hf_url: https://huggingface.co/deepseek-ai/DeepSeek-V2-Lite
trace_url: ''
workload:
  model:
    phase: inference
    moe: true
    granularity: model_fwd
    model_family: deepseek-v2-lite
    precision: bfloat16
  data:
    batch_size: 2
    seq_len: 8192
    dataset: synthetic
  hardware:
    network_topo:
      topology: slingshot
      bandwidth_gbps:
      - 200
      - 2000
    xpu_spec:
      type: GPU
      model: nvidia_a100
      total_count: 5
      count_per_node: 4
    driver_version: cuda_12.4
Model-executor:
  framework:
    name: vllm
    compiler_tool_selection: plain_pytorch
  model_plan_parallelization:
    dp_replicate: 1
    dp_shard: 1
    tp: 1
    pp: 1
    cp: 1
    ep: 1
  communication_library:
    name: NCCL
    version: 2.18+
    env:
      NCCL_IB_QPS_PER_CONNECTION: null
  protocol_selection:
  - rocev2
  - p2p
metric_source:
  traces:
  - torch_et
  - kineto_trace
  - nsys
  metrics_specific_trace: []
