from __future__ import annotations

from typing import Any

class TraceAnalysis:
    def __init__(self, trace_dir: str) -> None: ...
    def get_temporal_breakdown(self) -> Any: ...
    def get_comm_comp_overlap(self, visualize: bool = ...) -> Any: ...
    def get_gpu_kernel_breakdown(self, visualize: bool = ...) -> tuple[Any, Any] | Any: ...
    def get_step_time(self) -> dict[Any, Any] | Any: ...
    def get_step_time_series(self) -> dict[Any, Any] | Any: ...
    def get_step_time_df(self) -> Any: ...
