from __future__ import annotations

from typing import Any

class TraceAnalysis:
    def __init__(self, trace_dir: str) -> None: ...
    def get_temporal_breakdown(self) -> Any: ...
    def get_comm_comp_overlap(self) -> Any: ...
    def get_comm_stats(self) -> Any: ...
    def get_kernel_breakdown(self) -> Any: ...
