---
# workload_card.yaml - Qwen3-32B FSDP+TP Configuration
# Workload: qwen3-32b-torchtitan-fsdp+tp-perlmutter-16
version: 1

description: >
  Qwen3-32B training on 16 GPUs with FSDP + TP (2D) parallelism.
  4 Perlmutter GPU nodes (4 nodes × 4 GPUs = 16 GPUs total).
  Configuration: dp_shard=4, tp=4 (4-way FSDP + 4-way TP).
  TorchTitan framework with NCCL;
  uses all-reduce for both FSDP and TP gradient sync.

hf_url: https://huggingface.co/Qwen/Qwen3-32B
trace_url:  # TODO: Add Cornell Box link after uploading traces

workload:
  model:
    phase: training
    moe: true
    granularity: model_fwd_bwd_pass
    model_family: qwen3-32b
    precision: bf16
    epochs: 1
    iteration: 80
  data:
    batch_size: 4
    seq_len: 2048
    dataset: c4
  hardware:
    network_topo:
      topology: slingshot
      bandwidth_gbps:
        - 200  # Scale-out: 200 Gbps per NIC over Slingshot (inter-node)
        - 2000  # Scale-up: Approx NVLink/NVSwitch aggregate bandwidth (Gbps)
    xpu_spec:
      type: GPU
      model: nvidia_a100
      total_count: 16
      count_per_node: 4
    driver_version: cuda_12.4

Model-executor:
  framework:
    name: torchtitan
    compiler_tool_selection: plain_pytorch
  model_plan_parallelization:
    dp_replicate: 1
    dp_shard: 4
    tp: 4
    pp: 1
    cp: 1
    ep: 1
  communication_library:
    name: NCCL
    version: 2.18.5
    env:
      NCCL_IB_QPS_PER_CONNECTION: '4'
      NCCL_DEBUG: INFO
  protocol_selection:
    - rocev2  # Scale-out over Slingshot (inter-node communication)
    - p2p  # Intra-node GPUDirect/NVLink

metric_source:
  traces: [nsys, torch_et, kineto_trace]
  metrics_specific_trace:
    - nvtx_ranges  # For parallelism classification (FSDP/TP)
