# workload_template.yaml
version: 1

description: DeepSeek-V3 16B model training on Perlmutter using TorchTitan framework. The trace contains one training iteration.

hf_url: https://huggingface.co/deepseek-ai/deepseek-moe-16b-base
trace_url: /data/ccl-bench_trace_collection/deepseek-v3-16b-torchtitan-perlmutter

workload:
  model:
    phase: training
    moe: true
    granularity: model_fwd_bwd_pass
    model_family: deepseek_v3_16b
    precision: bf16
    epochs: 1
    iteration: 1
    model_arch:
      # DeepSeek-MoE-16B base architecture
      # Reference: https://huggingface.co/deepseek-ai/deepseek-moe-16b-base
      num_params: 16380544000         # total parameter count
      num_params_embedding: 204800000 # vocab_size(100000) * hidden_size(2048)
      num_layers: 28                  # L: transformer decoder layers
      num_heads: 16                   # Q: number of attention heads
      head_dim: 128                   # H: per-head dimension (hidden_size / num_heads)

  data:
    batch_size: 8
    seq_len: 2048
    dataset: c4_test
  hardware:
    network_topo:
      topology: slingshot
      bandwidth_gbps:
        - 200
        - 2400
    xpu_spec:
      type: GPU
      model: nvidia_a100
      total_count: 16
      count_per_node: 4
    driver_version: cuda_12.8

Model-executor:
  framework:
    name: torchtitan-0.1.0
    compiler_tool_selection: pytorch-2.10.0, triton
  model_plan_parallelization:
    dp_replicate: 1
    dp_shard: 2
    tp: 4
    pp: 2
    cp: 1
    ep: 8
    pp_mb: 2
  communication_library:
    name: NCCL
    version: 2.28.3
    env:
      NCCL_IB_QPS_PER_CONNECTION:
  protocol_selection:
    - rocev2
    - nvlink

metric_source:
  traces:
    - json
  metrics_specific_trace:
    - 