---
# workload_card.yaml - DeepSeek-V2-Lite (16B MoE) Configuration
# Workload: deepseek-v2-lite-torchtitan-4d-perlmutter-group-16
version: 1

description: >
  DeepSeek-V2-Lite (16B MoE) training on 8 GPUs with FSDP + TP + PP + EP
  parallelism. 2 Perlmutter GPU nodes (2 nodes × 4 GPUs = 8 GPUs total).
  Configuration: dp_replicate=1, dp_shard=2, tp=2, pp=2, cp=1, ep=4. TorchTitan
  framework with NCCL.

hf_url: https://huggingface.co/deepseek-ai/DeepSeek-V2-Lite
trace_url: https://drive.google.com/file/d/1nCu9Cy7VAcgtmSiI_vYtRKKOIIb5RgSk

workload:
  model:
    phase: training
    moe: true
    granularity: model_fwd_bwd_pass
    model_family: deepseek-v2-lite-16b
    precision: bf16
    epochs: 1
    iteration: 20
  data:
    batch_size: 2
    seq_len: 1024
    dataset: c4
  hardware:
    network_topo:
      topology: slingshot
      bandwidth_gbps:
        - 200  # Scale-out: 200 Gbps per NIC over Slingshot (inter-node)
        - 2000  # Scale-up: Approx NVLink/NVSwitch aggregate bandwidth (Gbps)
    xpu_spec:
      type: GPU
      model: nvidia_a100
      total_count: 8
      count_per_node: 4
    driver_version: cuda_12.4

Model-executor:
  framework:
    name: torchtitan
    compiler_tool_selection: plain_pytorch
  model_plan_parallelization:
    dp_replicate: 1
    dp_shard: 2
    tp: 2
    pp: 2
    cp: 1
    ep: 4
  communication_library:
    name: NCCL
    version: 2.18.5
    env:
      NCCL_IB_QPS_PER_CONNECTION: '4'
      NCCL_DEBUG: INFO
  protocol_selection:
    - rocev2  # Scale-out over Slingshot (inter-node communication)
    - p2p  # Intra-node GPUDirect/NVLink

metric_source:
  traces: [nsys, torch_et, kineto_trace]
  metrics_specific_trace:
    - nvtx_ranges  # For parallelism classification (FSDP/TP/PP/EP)
