---
# workload_card.yaml - DeepSeek-V2-Lite (16B MoE) FSDP+TP+EP Configuration
# Workload: deepseek-v2-lite-torchtitan-fsdp+tp+ep-perlmutter-16
version: 1

description: >
  DeepSeek-V2-Lite (16B MoE) training on 8 GPUs with FSDP + TP + EP (3D MoE).
  2 Perlmutter GPU nodes (2 nodes × 4 GPUs = 8 GPUs total).
  Configuration: dp_shard=2, tp=2, ep=4.
  3D MoE parallelism combining FSDP memory efficiency, TP matmul sharding,
  and EP expert distribution.
  TorchTitan framework with NCCL;
  uses all-reduce (FSDP/TP) and all-to-all (EP) communications.

hf_url: https://huggingface.co/deepseek-ai/DeepSeek-V2-Lite
trace_url:  # TODO: Add Cornell Box link after uploading traces

workload:
  model:
    phase: training
    moe: true
    granularity: model_fwd_bwd_pass
    model_family: deepseek-v2-lite
    precision: bf16
    epochs: 1
    iteration: 80
  data:
    batch_size: 4
    seq_len: 2048
    dataset: c4
  hardware:
    network_topo:
      topology: slingshot
      bandwidth_gbps:
        - 200  # Scale-out: 200 Gbps per NIC over Slingshot (inter-node)
        - 2000  # Scale-up: Approx NVLink/NVSwitch aggregate bandwidth (Gbps)
    xpu_spec:
      type: GPU
      model: nvidia_a100
      total_count: 8
      count_per_node: 4
    driver_version: cuda_12.4

Model-executor:
  framework:
    name: torchtitan
    compiler_tool_selection: plain_pytorch
  model_plan_parallelization:
    dp_replicate: 1
    dp_shard: 2
    tp: 2
    pp: 1
    cp: 1
    ep: 4
  communication_library:
    name: NCCL
    version: 2.18.5
    env:
      NCCL_IB_QPS_PER_CONNECTION: '4'
      NCCL_DEBUG: INFO
  protocol_selection:
    - rocev2  # Scale-out over Slingshot (inter-node communication)
    - p2p  # Intra-node GPUDirect/NVLink

metric_source:
  traces: [nsys, torch_et, kineto_trace]
  metrics_specific_trace:
    - nvtx_ranges  # For parallelism classification (FSDP/TP/EP)
