# workload_template.yaml
version: 1

description: >  
  Online serving of DeepSeek-V2-Lite on 4 A100 GPUs with EP=4.
  allgather_reducescatter(default) and naive kernels are used as AlltoAll backend.
  Script: run.sh


hf_url: https://huggingface.co/deepseek-ai/DeepSeek-V2-Lite/tree/main
trace_url: # trace url, e.g., https://drive.google.com/file/d/1EK_YROAho2sBvYVn8idF6DbnaG3SZ0he/view

workload:
  model:
    phase: inference
    moe: true  
    granularity: layer  
    model_family: deepseek_v2
    precision: bf16
  data:
    batch_size: 1
    seq_len: 2048
    dataset: wikitext
  hardware:
    network_topo:
      topology: slingshot
      bandwidth_gbps:
        - 200  
    xpu_spec:
      type: GPU 
      model: nvidia_a100
      total_count: 4
      count_per_node: 4  
    driver_version: cuda_12.4  
  
Model-executor:
  framework: 
    name: vllm
    compiler_tool_selection: 
  model_plan_parallelization:
    dp_replicate: 2
    dp_shard: 1
    tp: 2
    pp: 1
    cp: 1
  communication_library:
    name: NCCL
    version: 2.27.3
    env:
      NCCL_IB_QPS_PER_CONNECTION:  
      VLLM_ALL2ALL_BACKEND: allgather_reducescatter
  protocol_selection:
    - rocev2
    - p2p

metric_source:
  traces:
    -  nsys
  metrics_specific_trace:
    - communication_ratio, total_communication_time, total_kernel_time, break_down_steps