# workload_card.yaml - Qwen3-32B 3D Parallelism (DP+TP+PP) Configuration
# Workload: qwen3-32b-torchtitan-3d-perlmutter-16
version: 1

description: >
  Qwen3-32B training on 8 GPUs with 3D parallelism (DP + TP + PP).
  2 Perlmutter GPU nodes (2 nodes × 4 GPUs = 8 GPUs total).
  Configuration: dp_replicate=2, tp=2, pp=2.
  Full 3D parallel: 2 DP replicas × 2-way TP × 2-stage PP.
  TorchTitan framework with NCCL; combines all-reduce (TP/DP) and send/recv (PP).

hf_url: https://huggingface.co/Qwen/Qwen3-32B
trace_url:  # TODO: Add Cornell Box link after uploading traces

workload:
  model:
    phase: training
    moe: false
    granularity: model_fwd_bwd_pass
    model_family: qwen3-32b
    precision: bf16
    epochs: 1
    iteration: 80
  data:
    batch_size: 4
    seq_len: 2048
    dataset: c4
  hardware:
    network_topo:
      topology: slingshot
      bandwidth_gbps:
        - 200   # Scale-out: 200 Gbps per NIC over Slingshot (inter-node)
        - 2000  # Scale-up: Approx NVLink/NVSwitch aggregate bandwidth (Gbps)
    xpu_spec:
      type: GPU
      model: nvidia_a100
      total_count: 8
      count_per_node: 4
    driver_version: cuda_12.4

Model-executor:
  framework:
    name: torchtitan
    compiler_tool_selection: plain_pytorch
  model_plan_parallelization:
    dp_replicate: 2
    dp_shard: 1
    tp: 2
    pp: 2
    cp: 1
  communication_library:
    name: NCCL
    version: 2.18.5
    env:
      NCCL_IB_QPS_PER_CONNECTION: "4"
      NCCL_DEBUG: INFO
  protocol_selection:
    - rocev2  # Scale-out over Slingshot (inter-node communication)
    - p2p     # Intra-node GPUDirect/NVLink

metric_source:
  traces:
    - nsys
    - torch_et
    - kineto_trace
  metrics_specific_trace:
    - nvtx_ranges  # For parallelism classification (DP/TP/PP)
